POST http://localhost:8080/events
Content-Type: application/json

{
    "name":"test event",
    "description":"this is a test event",
    "location":"test location",
    "dateTime": "2024-03-14T15:30:00.000Z"
}